# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  build-tags: []

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

formatters:
  enable:
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import statements are formatted

linters:
  enable:
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused constants, variables, functions and types
    - misspell      # Finds commonly misspelled English words
    - bodyclose     # Check HTTP response bodies are closed
    - noctx         # Finds sending HTTP request without context.Context
    - rowserrcheck  # Check sql.Rows.Err is checked
    - sqlclosecheck # Check sql.Rows and sql.Stmt are closed
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - whitespace    # Check for unnecessary whitespace

  disable:
    - exhaustive    # Too strict for this project
    - godox         # Allows TODO/FIXME comments
    - wrapcheck     # Checks that errors are wrapped (too strict)
    - testpackage   # Forces tests in separate package (not desired)
    - revive        # Disabled: too many documentation requirements for active development
    - errcheck      # Disabled: all remaining issues were in test files
    - gosec         # Disabled: many false positives and test file issues

formatters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/soderasen-au/go-common

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow  # Too strict for this codebase

  misspell:
    locale: US

  unused:
    check-exported: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - .git
    - .github
    - .idea

  exclude-rules:
    # Exclude some linters from running on test files
    - path: ".*_test\\.go$"
      linters:
        - unparam
        - rowserrcheck
        - sqlclosecheck

    # Ignore staticcheck refactoring suggestions (non-critical)
    - linters:
        - staticcheck
      text: "(S1034|S1002|ST1023|QF1008|QF1011|QF1003):"  # Type assertions, bool comparisons, type inference, field selectors, switch suggestions

    # Ignore whitespace linting issues
    - linters:
        - whitespace
      text: ".*"

    # Ignore noctx issues (context requirements)
    - linters:
        - noctx
      text: ".*"
